import { DomainInvariantError } from "../domain/errors.js";
import type { EvidenceItem, EvidenceLink } from "../domain/evidence.js";
import type { Event } from "../domain/event.js";
import { readValidatedG0A2DisputeBoundary } from "./consolidate-g0a2-self-hypothesis-dispute.js";
import { buildG0A2SelfHypothesisLinkId } from "../domain/g0a2-self-hypothesis-consolidation.js";
import { buildRevisedG0A2SelfHypothesisId, planG0A2SelfHypothesisRevision, type G0A2RevisionObservation, type G0A2RevisionPlan } from "../domain/g0a2-self-hypothesis-revision.js";
import { propositionEquals, type Proposition } from "../domain/proposition.js";
import type { EntityId, SerializableValue, StateVersion } from "../domain/primitives.js";
import type { SelfHypothesis } from "../domain/self-hypothesis.js";
import { buildSelfHypothesisKey } from "../domain/self-hypothesis.js";
import type { AtomicCommitResult, PersistencePort } from "../ports/persistence.js";
import { validateEvidenceItem } from "./validate-evidence.js";

const SCOPE = "self_hypothesis_consolidation"; const AXIS = "decision_style_under_uncertainty";
export interface ConsolidateG0A2SelfHypothesisRevisionInput { readonly lenoSeedId: EntityId; readonly consolidationId: string; readonly systemSourceId: EntityId; readonly evidenceItemIds: readonly EntityId[]; readonly engineVersion: string; }
export interface ConsolidateG0A2SelfHypothesisRevisionResult { readonly outcome: "revise" | "no_change"; readonly selfHypothesisId: EntityId | null; readonly previousStateVersion: StateVersion; readonly newStateVersion: StateVersion; readonly changed: boolean; readonly replayed: boolean; }

export async function consolidateG0A2SelfHypothesisRevision(input: ConsolidateG0A2SelfHypothesisRevisionInput, persistence: PersistencePort): Promise<ConsolidateG0A2SelfHypothesisRevisionResult> {
  if ((await persistence.readSource(input.systemSourceId))?.kind !== "system") throw new DomainInvariantError("G0-A2 revision requires a system source");
  let checkpoint = findCheckpoint(await persistence.readEventsInSequence(input.lenoSeedId), input); let plan: G0A2RevisionPlan; let v2: SelfHypothesis;
  if (checkpoint !== null) ({ plan, v2 } = await parseCheckpoint(checkpoint, input, persistence));
  else {
    v2 = await readCurrentV2(input.lenoSeedId, persistence); const boundary = await readValidatedG0A2DisputeBoundary(input.lenoSeedId, v2, persistence); const observations = await readObservations(input, persistence);
    await validateSnapshot(observations, v2, boundary, persistence); plan = planG0A2SelfHypothesisRevision({ lenoSeedId: input.lenoSeedId, consolidationId: input.consolidationId, v2, observations });
    checkpoint = await appendCheckpoint(input, plan, observations, boundary.checkpoint, persistence);
  }
  const completion = findCompletion(await persistence.readEventsInSequence(input.lenoSeedId), input);
  if (completion !== null) { const result = validateCompletion(completion, checkpoint, plan, input); await validateDurable(plan, v2, input, persistence); return { outcome: plan.outcome, selfHypothesisId: plan.nextHypothesisSnapshot?.id ?? null, ...result, replayed: true }; }
  const superseded = plan.outcome === "revise" ? { ...v2, status: "superseded" as const, updatedAt: plan.timestamp } : null;
  const commit = await persistence.atomicCommit(input.lenoSeedId, checkpoint.observedStateVersion, { evidenceItems: [], evidenceLinks: plan.linkSnapshots, beliefs: [], selfHypotheses: superseded === null || plan.nextHypothesisSnapshot === null ? [] : [superseded, plan.nextHypothesisSnapshot] }, key(input, "commit"));
  await appendCompletion(input, checkpoint, plan, commit, persistence);
  return { outcome: plan.outcome, selfHypothesisId: plan.nextHypothesisSnapshot?.id ?? null, previousStateVersion: commit.previousStateVersion, newStateVersion: commit.newStateVersion, changed: commit.applied, replayed: false };
}

async function readCurrentV2(lenoSeedId: EntityId, persistence: PersistencePort): Promise<SelfHypothesis> {
  const keyValue = buildSelfHypothesisKey({ subjectRef: lenoSeedId, predicate: AXIS, value: "seek_clarification", context: { protocol: "G0-A2" } }); const history = await persistence.readSelfHypothesisHistoryByKey(lenoSeedId, keyValue);
  if (history.length !== 2) throw new DomainInvariantError("G0-A2 revision requires exactly v1 and v2"); const [v1, v2] = history;
  if (v1 === undefined || v2 === undefined || !coherentV1(v1, keyValue) || v1.status !== "superseded" || !coherentV2(v2, v1, keyValue) || v2.status !== "disputed") throw new DomainInvariantError("G0-A2 revision requires current disputed v2"); return v2;
}
async function readObservations(input: ConsolidateG0A2SelfHypothesisRevisionInput, persistence: PersistencePort): Promise<readonly G0A2RevisionObservation[]> {
  if (input.evidenceItemIds.length < 7 || input.evidenceItemIds.length > 8 || new Set(input.evidenceItemIds).size !== input.evidenceItemIds.length) throw new DomainInvariantError("G0-A2 revision requires seven or eight distinct observations"); const result: G0A2RevisionObservation[] = [];
  for (const id of input.evidenceItemIds) { const evidenceItem = await persistence.readEvidenceItem(input.lenoSeedId, id); if (evidenceItem === null || evidenceItem.kind !== "behavioral_observation" || evidenceItem.status !== "active" || evidenceItem.grounding?.kind !== "structured_event" || await validateEvidenceItem(evidenceItem, persistence) !== null) throw new DomainInvariantError(`G0-A2 revision observation ${id} is invalid`); const sourceEvent = await persistence.readEventById(input.lenoSeedId, evidenceItem.grounding.eventId); if (sourceEvent === null || sourceEvent.type !== "intention_selected" || sourceEvent.payloadSchemaVersion !== 2 || !Array.isArray(sourceEvent.payload.triggerSelfHypothesisIds) || !sourceEvent.payload.triggerSelfHypothesisIds.every((x) => typeof x === "string")) throw new DomainInvariantError(`G0-A2 revision observation ${id} source is invalid`); const triggerHypothesisKeys: string[] = []; for (const triggerId of sourceEvent.payload.triggerSelfHypothesisIds) { const trigger = await persistence.readSelfHypothesis(input.lenoSeedId, triggerId); if (trigger === null) throw new DomainInvariantError("G0-A2 revision trigger is unknown"); triggerHypothesisKeys.push(trigger.hypothesisKey); } result.push({ evidenceItem, sourceEvent, triggerHypothesisKeys }); }
  return result.sort((a, b) => a.sourceEvent.sequence - b.sourceEvent.sequence);
}
async function validateSnapshot(observations: readonly G0A2RevisionObservation[], v2: SelfHypothesis, boundary: { checkpoint: Event; completion: Event }, persistence: PersistencePort): Promise<void> {
  const situations = new Set<string>(); for (const o of observations) { const s = o.evidenceItem.proposition.context.situationId; const triggers = o.sourceEvent.payload.triggerSelfHypothesisIds; if (typeof s !== "string" || !["S1", "S2", "S3", "S4", "R1", "R2", "R3", "S5"].includes(s) || situations.has(s)) throw new DomainInvariantError("G0-A2 revision snapshot situations invalid"); situations.add(s); if (["R1", "R2", "R3"].includes(s) && (!Array.isArray(triggers) || triggers.length !== 0)) throw new DomainInvariantError("G0-A2 revision observations must be clean"); if (s === "R3" && o.sourceEvent.sequence <= boundary.completion.sequence) throw new DomainInvariantError("G0-A2 revision R3 predates disputed v2"); }
  if (["S1", "S2", "S3", "S4", "R1", "R2", "R3"].some((s) => !situations.has(s))) throw new DomainInvariantError("G0-A2 revision snapshot is incomplete");
  const retained = new Set<EntityId>(); for (const linkId of [...v2.supportLinkIds, ...v2.againstLinkIds]) { const link = await persistence.readEvidenceLink(v2.lenoSeedId, linkId); if (link === null || link.targetId !== v2.id) throw new DomainInvariantError("G0-A2 revision v2 links invalid"); retained.add(link.evidenceItemId); } for (const o of observations) { const s = o.evidenceItem.proposition.context.situationId; if (s !== "R3" && s !== "S5" && !retained.has(o.evidenceItem.id)) throw new DomainInvariantError("G0-A2 revision substitutes v2 evidence"); }
}
async function appendCheckpoint(input: ConsolidateG0A2SelfHypothesisRevisionInput, plan: G0A2RevisionPlan, observations: readonly G0A2RevisionObservation[], dispute: Event, persistence: PersistencePort): Promise<Event> { const events = await persistence.readEventsInSequence(input.lenoSeedId); const causes = [...observations.map((o) => o.sourceEvent.id), dispute.id]; if (new Set(causes).size !== causes.length) throw new DomainInvariantError("G0-A2 revision causes duplicate"); const event: Event = { id: id(input, "decision"), lenoSeedId: input.lenoSeedId, sequence: (events.at(-1)?.sequence ?? 0) + 1, type: "validation_decision_recorded", occurredAt: plan.timestamp, turnId: null, sourceId: input.systemSourceId, actorRef: null, causedByEventIds: causes, observedStateVersion: await persistence.getStateVersion(input.lenoSeedId), payload: serialize(plan, input), payloadSchemaVersion: 3, engineVersion: input.engineVersion, idempotencyKey: key(input, "decision") }; await persistence.appendEvent(event); return event; }
async function appendCompletion(input: ConsolidateG0A2SelfHypothesisRevisionInput, checkpoint: Event, plan: G0A2RevisionPlan, commit: AtomicCommitResult, persistence: PersistencePort): Promise<void> { const events = await persistence.readEventsInSequence(input.lenoSeedId); await persistence.appendEvent({ id: id(input, "completed"), lenoSeedId: input.lenoSeedId, sequence: (events.at(-1)?.sequence ?? 0) + 1, type: "state_commit_completed", occurredAt: plan.timestamp, turnId: null, sourceId: input.systemSourceId, actorRef: null, causedByEventIds: [checkpoint.id], observedStateVersion: commit.previousStateVersion, payload: { scope: SCOPE, consolidationId: input.consolidationId, previousStateVersion: commit.previousStateVersion, newStateVersion: commit.newStateVersion, changed: commit.applied }, payloadSchemaVersion: 2, engineVersion: input.engineVersion, idempotencyKey: key(input, "completed") }); }
function findCheckpoint(events: readonly Event[], input: ConsolidateG0A2SelfHypothesisRevisionInput): Event | null { const found = events.filter((e) => e.id === id(input, "decision") || e.idempotencyKey === key(input, "decision") || (e.type === "validation_decision_recorded" && e.payloadSchemaVersion === 3 && e.payload.scope === SCOPE && e.payload.consolidationId === input.consolidationId)); if (found.length > 1) throw new DomainInvariantError("G0-A2 revision multiple checkpoints"); return found[0] ?? null; }
function findCompletion(events: readonly Event[], input: ConsolidateG0A2SelfHypothesisRevisionInput): Event | null { const found = events.filter((e) => e.id === id(input, "completed") || e.idempotencyKey === key(input, "completed") || (e.type === "state_commit_completed" && e.payloadSchemaVersion === 2 && e.payload.scope === SCOPE && e.payload.consolidationId === input.consolidationId)); if (found.length > 1) throw new DomainInvariantError("G0-A2 revision multiple completions"); return found[0] ?? null; }
async function parseCheckpoint(event: Event, input: ConsolidateG0A2SelfHypothesisRevisionInput, persistence: PersistencePort): Promise<{ plan: G0A2RevisionPlan; v2: SelfHypothesis }> {
  if (event.id !== id(input, "decision") || event.lenoSeedId !== input.lenoSeedId || event.type !== "validation_decision_recorded" || event.payloadSchemaVersion !== 3 || event.idempotencyKey !== key(input, "decision") || event.turnId !== null || event.sourceId !== input.systemSourceId || event.actorRef !== null || event.engineVersion !== input.engineVersion || !version(event.observedStateVersion)) throw new DomainInvariantError("G0-A2 revision checkpoint identity incoherent");
  const p = object(event.payload); if (p.scope !== SCOPE || p.consolidationId !== input.consolidationId || (p.outcome !== "revise" && p.outcome !== "no_change")) throw new DomainInvariantError("G0-A2 revision checkpoint scope incoherent");
  const candidate = proposition(p.candidateProposition); const hypothesisKey = text(p.hypothesisKey); if (buildSelfHypothesisKey(candidate) !== hypothesisKey) throw new DomainInvariantError("G0-A2 revision checkpoint key incoherent");
  const evidenceIds = texts(p.inputEvidenceItemIds); if (!sameSet(evidenceIds, input.evidenceItemIds)) throw new DomainInvariantError("G0-A2 revision checkpoint input conflicts");
  const supersededId = p.supersededHypothesisId === null ? null : text(p.supersededHypothesisId); const v2 = await historicalV2(input.lenoSeedId, supersededId, p.outcome, persistence);
  const boundary = await readValidatedG0A2DisputeBoundary(input.lenoSeedId, v2, persistence); const observations = await readObservations(input, persistence); await validateSnapshot(observations, v2, boundary, persistence);
  const canonical = observations.map((o) => o.evidenceItem.id); const timestamp = observations.at(-1)?.sourceEvent.occurredAt; if (timestamp === undefined || event.occurredAt !== timestamp || !sameList(evidenceIds, canonical) || !sameList(event.causedByEventIds, [...observations.map((o) => o.sourceEvent.id), boundary.checkpoint.id])) throw new DomainInvariantError("G0-A2 revision checkpoint provenance incoherent");
  const links = linksOf(p.linkSnapshots); const support = texts(p.countedSupportGroups); const against = texts(p.countedAgainstGroups); const ignored = texts(p.ignoredContaminatedLinkIds); const next = p.nextHypothesisSnapshot === null ? null : hypothesis(p.nextHypothesisSnapshot);
  const expectedCandidate = { ...v2.proposition, value: v2.proposition.value === "seek_clarification" ? "use_available_information" : "seek_clarification" }; if (!propositionEquals(candidate, expectedCandidate)) throw new DomainInvariantError("G0-A2 revision candidate is not opposite");
  const planningV2 = v2.status === "superseded" ? { ...v2, status: "disputed" as const } : v2;
  const expected = planG0A2SelfHypothesisRevision({ lenoSeedId: input.lenoSeedId, consolidationId: input.consolidationId, v2: planningV2, observations });
  if (!sameList(support, expected.countedSupportGroups) || !sameList(against, expected.countedAgainstGroups) || !sameList(ignored, expected.ignoredContaminatedLinkIds)) throw new DomainInvariantError("G0-A2 revision checkpoint groups incoherent");
  if (p.outcome === "no_change") { if (next !== null || links.length !== 0 || supersededId !== null) throw new DomainInvariantError("G0-A2 revision no_change snapshots invalid"); return { v2, plan: { ...expected, outcome: "no_change", linkSnapshots: [], nextHypothesisSnapshot: null, supersededHypothesisId: null } }; }
  if (supersededId !== v2.id || next === null || !sameLinks(links, expected.linkSnapshots) || !sameHypothesis(next, expected.nextHypothesisSnapshot)) throw new DomainInvariantError("G0-A2 revision checkpoint snapshots incoherent");
  return { v2, plan: { ...expected, outcome: "revise", linkSnapshots: links, nextHypothesisSnapshot: next, supersededHypothesisId: supersededId } };
}
async function historicalV2(lenoSeedId: EntityId, idValue: EntityId | null, outcome: string, persistence: PersistencePort): Promise<SelfHypothesis> { if (outcome !== "revise" || idValue === null) { const keyValue = buildSelfHypothesisKey({ subjectRef: lenoSeedId, predicate: AXIS, value: "seek_clarification", context: { protocol: "G0-A2" } }); const history = await persistence.readSelfHypothesisHistoryByKey(lenoSeedId, keyValue); const v2 = history.find((h) => h.version === 2); if (v2 === undefined) throw new DomainInvariantError("G0-A2 revision v2 missing"); return v2; } const v2 = await persistence.readSelfHypothesis(lenoSeedId, idValue); if (v2 === null) throw new DomainInvariantError("G0-A2 revision v2 missing"); return v2; }
function validateCompletion(event: Event, checkpoint: Event, plan: G0A2RevisionPlan, input: ConsolidateG0A2SelfHypothesisRevisionInput): Omit<ConsolidateG0A2SelfHypothesisRevisionResult, "outcome" | "selfHypothesisId" | "replayed"> { const p = object(event.payload); const previous = p.previousStateVersion; const next = p.newStateVersion; if (event.id !== id(input, "completed") || event.lenoSeedId !== input.lenoSeedId || event.type !== "state_commit_completed" || event.payloadSchemaVersion !== 2 || event.turnId !== null || event.sourceId !== input.systemSourceId || event.actorRef !== null || event.engineVersion !== input.engineVersion || event.idempotencyKey !== key(input, "completed") || !sameList(event.causedByEventIds, [checkpoint.id]) || event.occurredAt !== plan.timestamp || p.scope !== SCOPE || p.consolidationId !== input.consolidationId || !version(previous) || !version(next) || event.observedStateVersion !== previous || previous !== checkpoint.observedStateVersion || typeof p.changed !== "boolean" || p.changed !== (plan.outcome === "revise") || next !== previous + (p.changed ? 1 : 0)) throw new DomainInvariantError("G0-A2 revision completion incoherent"); return { previousStateVersion: previous, newStateVersion: next, changed: p.changed }; }
async function validateDurable(plan: G0A2RevisionPlan, v2: SelfHypothesis, input: ConsolidateG0A2SelfHypothesisRevisionInput, persistence: PersistencePort): Promise<void> { if (plan.outcome === "no_change") { if (await persistence.readSelfHypothesis(input.lenoSeedId, buildRevisedG0A2SelfHypothesisId(input.lenoSeedId, input.consolidationId)) !== null) throw new DomainInvariantError("G0-A2 revision no_change v3 exists"); return; } if (v2.status !== "superseded") throw new DomainInvariantError("G0-A2 revision durable v2 incoherent"); const next = plan.nextHypothesisSnapshot; if (next === null) throw new DomainInvariantError("G0-A2 revision v3 missing"); const actual = await persistence.readSelfHypothesis(input.lenoSeedId, next.id); if (actual === null || !sameImmutable(actual, next) || (actual.status !== "active" && actual.status !== "superseded")) throw new DomainInvariantError("G0-A2 revision durable v3 incoherent"); for (const link of plan.linkSnapshots) if (!sameLink(await persistence.readEvidenceLink(input.lenoSeedId, link.id), link)) throw new DomainInvariantError("G0-A2 revision links incoherent"); }
function serialize(plan: G0A2RevisionPlan, input: ConsolidateG0A2SelfHypothesisRevisionInput): Readonly<Record<string, SerializableValue>> { return { scope: SCOPE, consolidationId: input.consolidationId, hypothesisKey: plan.hypothesisKey, candidateProposition: propSerializable(plan.candidateProposition), inputEvidenceItemIds: [...plan.inputEvidenceItemIds], countedSupportGroups: [...plan.countedSupportGroups], countedAgainstGroups: [...plan.countedAgainstGroups], ignoredContaminatedLinkIds: [...plan.ignoredContaminatedLinkIds], outcome: plan.outcome, linkSnapshots: plan.linkSnapshots.map((x) => ({ ...x })), nextHypothesisSnapshot: plan.nextHypothesisSnapshot === null ? null : hypSerializable(plan.nextHypothesisSnapshot), supersededHypothesisId: plan.supersededHypothesisId }; }
function coherentV1(v1: SelfHypothesis, keyValue: string): boolean { return v1.version === 1 && v1.confidence === "moderate" && v1.stage === "hypothesis" && v1.hypothesisKey === keyValue && v1.previousVersionId === null; }
function coherentV2(v2: SelfHypothesis, v1: SelfHypothesis, keyValue: string): boolean { return v2.version === 2 && v2.confidence === "low" && v2.stage === "hypothesis" && v2.hypothesisKey === keyValue && v2.previousVersionId === v1.id && propositionEquals(v2.proposition, v1.proposition); }
function object(value: unknown): Record<string, any> { if (value === null || typeof value !== "object" || Array.isArray(value)) throw new DomainInvariantError("G0-A2 revision snapshot malformed"); return value as Record<string, any>; }
function text(value: unknown): string { if (typeof value !== "string") throw new DomainInvariantError("G0-A2 revision snapshot malformed"); return value; }
function texts(value: unknown): readonly string[] { if (!Array.isArray(value) || !value.every((x) => typeof x === "string")) throw new DomainInvariantError("G0-A2 revision snapshot malformed"); return value as string[]; }
function proposition(value: unknown): Proposition { const p = object(value); const context = object(p.context); if (typeof p.subjectRef !== "string" || typeof p.predicate !== "string" || !["seek_clarification", "use_available_information"].includes(p.value) || context.protocol !== "G0-A2") throw new DomainInvariantError("G0-A2 revision proposition malformed"); return { subjectRef: p.subjectRef, predicate: p.predicate, value: p.value, context }; }
function hypothesis(value: unknown): SelfHypothesis { return object(value) as SelfHypothesis; }
function linksOf(value: unknown): readonly EvidenceLink[] { if (!Array.isArray(value)) throw new DomainInvariantError("G0-A2 revision links malformed"); return value as EvidenceLink[]; }
function sameLinks(left: readonly EvidenceLink[], right: readonly EvidenceLink[]): boolean { return left.length === right.length && left.every((x, i) => sameLink(x, right[i] ?? null)); }
function sameLink(left: EvidenceLink | null, right: EvidenceLink | null): boolean { return left !== null && right !== null && JSON.stringify(left) === JSON.stringify(right); }
function sameHypothesis(left: SelfHypothesis, right: SelfHypothesis | null): boolean { return right !== null && JSON.stringify(left) === JSON.stringify(right); }
function sameImmutable(left: SelfHypothesis, right: SelfHypothesis): boolean { return left.id === right.id && left.lenoSeedId === right.lenoSeedId && left.hypothesisKey === right.hypothesisKey && left.version === right.version && propositionEquals(left.proposition, right.proposition) && left.stage === right.stage && JSON.stringify(left.supportLinkIds) === JSON.stringify(right.supportLinkIds) && JSON.stringify(left.againstLinkIds) === JSON.stringify(right.againstLinkIds) && left.confidence === right.confidence && left.previousVersionId === right.previousVersionId && left.createdAt === right.createdAt; }
function propSerializable(value: Proposition): SerializableValue { return { subjectRef: value.subjectRef, predicate: value.predicate, value: value.value, context: { ...value.context } }; }
function hypSerializable(value: SelfHypothesis): SerializableValue { return { ...value, proposition: propSerializable(value.proposition), supportLinkIds: [...value.supportLinkIds], againstLinkIds: [...value.againstLinkIds] }; }
function snapshotId(value: unknown): string | null { return value !== null && typeof value === "object" && typeof (value as { id?: unknown }).id === "string" ? (value as { id: string }).id : null; }
function version(value: unknown): value is number { return typeof value === "number" && Number.isInteger(value) && value >= 0; }
function sameList(a: readonly string[], b: readonly string[]): boolean { return a.length === b.length && a.every((x, i) => x === b[i]); }
function sameSet(a: readonly string[], b: readonly string[]): boolean { return a.length === b.length && new Set(a).size === a.length && a.every((x) => b.includes(x)); }
function id(input: ConsolidateG0A2SelfHypothesisRevisionInput, suffix: string): EntityId { return `E-G0A2-${input.lenoSeedId}-${input.consolidationId}-${suffix}`; }
function key(input: ConsolidateG0A2SelfHypothesisRevisionInput, suffix: string): string { return `g0a2:${input.lenoSeedId}:${input.consolidationId}:${suffix}`; }
